# For remote themes: commented for now, first install bundle (Gemfile)
#plugins:
#  - jekyll-remote-theme
#remote_theme: sharu725/hagura

theme: jekyll-theme-minimal
title: Shubham TRIVEDI
show_downloads: false
google_analytics: UA-111533371-1
